### ISSUE TITLE
Guide on how to use Angular templates

### ISSUE THREAD

**Issue by kvnwolf** [nickjanssen/angus#16]
Hello all!

First of all, I want to congratulate all commiters on this project, it is **awesome**.

Now, I want to ask the following question: I am creating an AngularJS application using modular design, in which I place the view templates inside _core/[module name]/[module name].tpl.html_. But they are not compiling into the _dist_ folder.

Why is this happening?

**Comment by kvnwolf** [comment]
Never mind, I found the way. The templates file are generated on `js/html2js/core/chat/chatTpl.js` and I just had to include `angus.templates.app` as a module dependency of my app ;).

**Comment by nickjanssen** [comment]
Thank you for the kind words :) I'm happy that you got it working! Let me know if you have additional questions.
