### ISSUE TITLE
Quickstart issue?

### ISSUE THREAD

**Issue by morritza** [nickjanssen/angus#17]
Hi, i tried to reproduce the following folder structur with the quickstart guide in the description, but it failed:

```
angus/   <-- angus repository
    Gruntfile.js
    grunt/   <-- generic build tasks
    apps/
        hello-world/
        my-second-app/    <-- app sub repository
            assets/
            scss/
            app.js
            config.js
            index.html

```

Its the example of the article on davidwalsh, could you extend the quickstart guide to get this work?

When i create a folder, the asses are generated correct but, there is no global grunt folder.
It would be nice if you could provide me with a guide or example config

**Comment by nickjanssen** [comment]
Hi @morritza! As of version 0.2, Angus now uses GulpJS to do the heavy-lifting of building your app. The article from David Walsh is fairly outdated, please see the [new app structure](https://github.com/nickjanssen/angus#app-structure).

In fact the whole readme is updated and it includes a Getting Started guide. Please check it out and let me know if you have additional questions.
