### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by RogueSheep-nl** [nickjanssen/angus#18]
What (initial) permissions does Angus require to create and run?

On the first attempt the 'create' died with:

```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/usr/local/lib/node_modules/angus/config.json'
    at Object.fs.openSync (fs.js:427:18)
```

Running it sudo-style fixed things but then the 'run' process seemed to get stuck on 'installing bootstrap'
Again sudo helped me out here :-)

After this the non-sudo commands seem to work fine. 

Thanks!

**Comment by nickjanssen** [comment]
To be honest, I don't need to use sudo on my machine (mac) so I'm not entirely sure what could be wrong there. I'm also not a users/permissions expert. On what system are you?

**Comment by RogueSheep-nl** [comment]
Thanks for your quick reply.
I didn't expect to run into these, my other npm installs worked fine. I'm also no expert on this but my educated guess is the inititial permissions on the folder in which to install were not set correctly.

Because the sudo did solve the problems, maybe you could add the 'run-like-sudo' option to the readme for those running into the same issue.

I am on OSX 10.8

**Comment by nickjanssen** [comment]
Thanks, I added a warning to the Readme!
