### ISSUE TITLE
Doesn't support coffee

### ISSUE THREAD

**Issue by sdaitzman** [nickjanssen/angus#20]
I :heart: :coffee:

**Comment by nickjanssen** [comment]
Coffeescript support landed in 0.10.0, check it out!
https://github.com/nickjanssen/angus/commit/2dba0e459f84b429c81c49fb9070529c2a6a06ef

Feel free to re-open this ticket if you would like to see additional features.

**Comment by sdaitzman** [comment]
Thank you very much :D that was all that was missing for me to start using Angus
